# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a65bfa8017d3c7c91fc8104958b74a34b670794fbe8ad46c548b693d8b20de718dcda0d089f3b5d9f05e25a8e7e3d100d299157ed0b5e913346382a88a2bad3

test:
  secret_key_base: d8a50d7cb6d77a9e8affe635d23706a7daa8ea6e4c96be64e336ea305dcedcbd6ca3d916236b18e57fb2f2d1c00aeb130d890a58469eef05b745350631fb85ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
